### ISSUE TITLE
extract images  error

### ISSUE THREAD

**Issue by goldyaphets** [Stirling-Tools/Stirling-PDF#1079] opened 2024-04-17 07:22 UTC
![extracterror](https://github.com/Stirling-Tools/Stirling-PDF/assets/120435311/e8762bcc-f348-4695-bdce-e3db2d47da57)

when i  extract images from a pdf , it says   Internal Server Error:LCMS error 13: Mismatched alpha channels

**Comment by goldyaphets** [comment] 2024-04-17 07:22
but i use the demo url   ,it can extract successfully

**Comment by sbplat** [comment] 2024-04-19 01:44
Are you on the latest version?

**Comment by Frooodle** [comment] 2024-06-01 14:43
duplicate of #1024

**Closed by Frooodle** 2024-06-01 14:43 UTC
Labels: needs investigation
