### ISSUE TITLE
[Feature Request]: Barcode splitter

### ISSUE THREAD

**Issue by Lheriss** [Stirling-Tools/Stirling-PDF#1911] opened 2024-09-15 21:19 UTC
### Feature Description

Hi,
I use barcode sticker/stamp on the first page of my multi pages documents, and then scan the whole batch.
It would be awsome to have a tool allowing to split the PDF when it detects a barcode (keeping the page where the barcode is). It's a tool you find on certain PDF Web services (like https://pdf4me.com/blog/split-pdf-by-barcode/)
Thanks for the great product!

### Why is this feature valuable?

The abilty to automatically split a PDF without having to insert a "blank page" with QR-Code...

### No Duplicate of the Feature

- [x] I have verified that there are no existing features requests similar to my request.

**Comment by tymanthius** [comment] 2024-09-19 21:15
This may be eligible to merge with #1737.  Similar ideas, but I'm not sure if the implementation would be completely different or not.

**Comment by Frooodle** [comment] 2024-12-13 13:07
duplicate of #1073

**Closed by Frooodle** 2024-12-13 13:07 UTC
Labels: enhancement
