### ISSUE TITLE
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping

### ISSUE THREAD

**Issue by trickyhi** [Stirling-Tools/Stirling-PDF#843] opened 2024-02-20 18:54 UTC
Getting the following error when trying to start the latest docker update. 
Rolling back to 0.20.2 gives the same error.

```
Picked up JAVA_TOOL_OPTIONS:  -XX:MaxRAMPercentage=75
Copying original files without overwriting existing files
Running Stirling PDF with DOCKER_ENABLE_SECURITY=false and VERSION_TAG=0.21.0
10:41:11.169 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 25, column 3:
      enabled: true # 'true' to enable ... 
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 26, column 5:
        installBookFormats: false # Inst ... 
        ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:654)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:162)
        at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:515)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:203)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:169)
        at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
        at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
        at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:54)
        at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:36)
        at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:96)
        at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132)
        at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87)
        at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:115)
        at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:242)
        at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:229)
        at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
        at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:137)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:369)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:329)
        at stirling.software.SPDF.SPdfApplication.main(SPdfApplication.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
```

**Comment by sbplat** [comment] 2024-02-20 18:59
Duplicate of #808

**Closed by sbplat** 2024-02-20 18:59 UTC

**Comment by Frooodle** [comment] 2024-02-20 19:25
As the above issue says 
Delete the /configs/settings.yml file and restart Stirling pdf 
It should be recreated correctly

**Comment by trickyhi** [comment] 2024-03-20 14:10
Thanks for your help,  deleting the config and restarting worked.
