### ISSUE TITLE
Cleanup Scans / OCR error

### ISSUE THREAD

**Issue by marcofenoglio** [Stirling-Tools/Stirling-PDF#1329] opened 2024-05-30 08:21 UTC
Docker Version 0.25.0 in Ubuntu 16.04TLS

Error log:
```
08:18:50.766 [qtp2053647669-44] INFO  s.s.SPDF.utils.ProcessExecutor - Running command: ocrmypdf --verbose 2 --output-type pdf --pdf-renderer hocr --deskew --clean --skip-text --language eng /tmp/input_5947355544812649658.pdf /tmp/output_7993803185626034787.pdf
08:18:53.263 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf - ocrmypdf 16.1.1
08:18:53.263 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['unpaper', '--version']
08:18:53.976 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Found unpaper 7.0.0
08:18:53.976 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
08:18:54.015 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Found tesseract 5.3.4
08:18:54.015 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
08:18:54.023 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
08:18:54.084 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Found gs 10.2.1
08:18:54.084 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
08:18:54.099 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
08:18:54.134 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = [DS] Profile read from file (tesseract_opencl_profile_devices.dat).
08:18:54.135 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor - [DS] Device[1] 0:(null) score is 0.261972
08:18:54.139 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor - [DS] Selected Device[1]: "(null)" (Native)
08:18:54.139 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor - List of available languages in "/usr/share/tessdata/" (1):
08:18:54.139 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor - eng
08:18:54.139 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -
08:18:54.140 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.helpers - pikepdf mmap enabled
08:18:54.140 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   ERROR ocrmypdf._pipelines._common - ExitCodeException
08:18:54.140 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor - Traceback (most recent call last):
08:18:54.140 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py", line 249, in cli_exception_handler
08:18:54.140 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -     return fn(options, plugin_manager)
08:18:54.140 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
08:18:54.140 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 166, in _run_pipeline
08:18:54.141 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -     check_requested_output_file(options)
08:18:54.141 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -   File "/usr/lib/python3.12/site-packages/ocrmypdf/_validation.py", line 310, in check_requested_output_file
08:18:54.141 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor -     raise OutputFileAccessError(
08:18:54.141 [Thread-15] INFO  s.s.SPDF.utils.ProcessExecutor - ocrmypdf.exceptions.OutputFileAccessError: Output file location (/tmp/output_7993803185626034787.pdf) is not a writable file.
08:18:54.243 [qtp2053647669-44] WARN  o.e.j.ee10.servlet.ServletChannel - handleException /api/v1/misc/ocr-pdf java.io.IOException: Command process failed with exit code 5. Error message:   DEBUG ocrmypdf - ocrmypdf 16.1.1
  DEBUG ocrmypdf.subprocess - Running: ['unpaper', '--version']
  DEBUG ocrmypdf.subprocess - Found unpaper 7.0.0
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 5.3.4
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 10.2.1
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = [DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 0:(null) score is 0.261972
[DS] Selected Device[1]: "(null)" (Native)
List of available languages in "/usr/share/tessdata/" (1):
eng

  DEBUG ocrmypdf.helpers - pikepdf mmap enabled
  ERROR ocrmypdf._pipelines._common - ExitCodeException
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py", line 249, in cli_exception_handler
    return fn(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 166, in _run_pipeline
    check_requested_output_file(options)
  File "/usr/lib/python3.12/site-packages/ocrmypdf/_validation.py", line 310, in check_requested_output_file
    raise OutputFileAccessError(
ocrmypdf.exceptions.OutputFileAccessError: Output file location (/tmp/output_7993803185626034787.pdf) is not a writable file.
```

**Comment by Frooodle** [comment] 2024-06-01 16:58
Based on write errors i assume its a permission issue, are you running it as a certain user or GUID etc that might be causing issues?

**Comment by Frooodle** [comment] 2024-06-01 16:58
or volume mapping the /tmp file causing some issue etc

**Comment by marcofenoglio** [comment] 2024-06-03 15:53
This is my docker command:
```
docker run -d  \
  -p 9284:4443 \
  -e DOCKER_ENABLE_SECURITY=false \
  -e INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false \
  -e LANGS=it_IT,en_GB \
  -v /mnt/data/docker_data/stirling-pdf/trainingData:/usr/share/tessdata \
  -v /mnt/data/docker_data/stirling-pdf/extraConfigs:/configs \
  -v /mnt/data/docker_data/stirling-pdf/logs:/logs \
  -v /etc/letsencrypt/live/<mydomain>/cert.pem:/configs/cert.pem \
  -v /etc/letsencrypt/live/<mydomain>/privkey.pem:/configs/privkey.pem \
  --name stirling-pdf \
  --restart unless-stopped \
  frooodle/s-pdf:latest
```
GUID and UID are the default.
And this is the volume directory stucture:
```
stirling-pdf/:
total 12
drwxr-xr-x 2 1000 1000 4096 May 29 11:15 extraConfigs
drwxr-xr-x 2 1000 1000 4096 Jun  2 22:19 logs
drwxr-xr-x 4 1000 1000 4096 May 29 09:52 trainingData

stirling-pdf/extraConfigs:
total 8
-rwxr-xr-x 1 1000 1000    0 May 29 10:22 cert.pem
-rwxr-xr-x 1 1000 1000  155 May 29 10:35 custom_settings.yml
-rwxr-xr-x 1 1000 1000    0 May 29 10:22 privkey.pem
-rwxr-xr-x 1 1000 1000 3633 Jun  2 22:19 settings.yml

stirling-pdf/logs:
total 8
-rw-r--r-- 1 1000 1000 4103 Jun  2 22:19 info.log
-rwxr-xr-x 1 1000 1000    0 May 29 09:52 invalid-auths.log

stirling-pdf/trainingData:
total 22932
drwxr-xr-x 2 1000 1000     4096 May 29 09:52 configs
-rwxr-xr-x 1 1000 1000 23466654 May 29 09:52 eng.traineddata
-rwxr-xr-x 1 1000 1000      572 May 29 09:52 pdf.ttf
drwxr-xr-x 2 1000 1000     4096 May 29 09:52 tessconfigs
```

**Comment by Frooodle** [comment] 2024-06-03 17:15
Looks like a bug with the "Correct pages were scanned at a skewed angle by rotating them back into place" feature if you have that enabled

**Comment by marcofenoglio** [comment] 2024-06-03 17:47
Same error without "deskew" option.

**Comment by Frooodle** [comment] 2024-08-03 14:51
Sorry for late reply, Does this still happen on latest version? closing ticket for now but happy to re-open if you can still reproduce

**Closed by Frooodle** 2024-08-03 14:51 UTC

**Comment by marcofenoglio** [comment] 2024-09-17 12:08
I tried with the new version 0.29.0 and I still get the same error. This is the temp directory situation during OCR:
`
drwxr-xr-x 2 1000 1000    4096 Sep 17 13:52 hsperfdata_stirlingpdfuser
-rw------- 1 1000 1000 1776855 Sep 17 13:58 input_12592559430707309562.pdf
drwxr-xr-x 2 1000 1000    4096 Sep 17 13:58 jetty-0_0_0_0-8080--_pdf-any-e218fc0e-7bcf-429f-9fdf-6fcb1bb0c0c0
drwx------ 2 1000 1000    4096 Sep 17 13:52 jetty-docbase.8080.12169003338244867909
-rw------- 1 1000 1000       0 Sep 17 13:58 output_16848536940110331072.pdf
-rw-r--r-- 1 1000 1000    6512 Sep 17 13:52 settings.yml9633507050184147827.template
`
and this is the log:
`
12:06:39.569 [qtp2050525584-35] INFO  s.s.SPDF.utils.ProcessExecutor - Running command: ocrmypdf --verbose 2 --output-type pdf --pdf-renderer hocr --deskew --skip-text --language eng /tmp/input_12592559430707309562.pdf /tmp/output_16848536940110331072.pdf
12:06:40.226 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf - ocrmypdf 16.1.1
12:06:40.226 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
12:06:40.234 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Found tesseract 5.3.4
12:06:40.235 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
12:06:40.243 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
12:06:40.258 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Found gs 10.3.1
12:06:40.258 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
12:06:40.274 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
12:06:40.286 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = [DS] Profile read from file (tesseract_opencl_profile_devices.dat).
12:06:40.287 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor - [DS] Device[1] 0:(null) score is 0.390008
12:06:40.287 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor - [DS] Selected Device[1]: "(null)" (Native)
12:06:40.288 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor - List of available languages in "/usr/share/tessdata/" (1):
12:06:40.288 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor - eng
12:06:40.289 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -
12:06:40.289 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   DEBUG ocrmypdf.helpers - pikepdf mmap enabled
12:06:40.291 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   ERROR ocrmypdf._pipelines._common - ExitCodeException
12:06:40.292 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor - Traceback (most recent call last):
12:06:40.292 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py", line 249, in cli_exception_handler
12:06:40.293 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -     return fn(options, plugin_manager)
12:06:40.294 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
12:06:40.294 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 166, in _run_pipeline
12:06:40.295 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -     check_requested_output_file(options)
12:06:40.295 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -   File "/usr/lib/python3.12/site-packages/ocrmypdf/_validation.py", line 310, in check_requested_output_file
12:06:40.295 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor -     raise OutputFileAccessError(
12:06:40.296 [Thread-23] INFO  s.s.SPDF.utils.ProcessExecutor - ocrmypdf.exceptions.OutputFileAccessError: Output file location (/tmp/output_16848536940110331072.pdf) is not a writable file.
12:06:40.419 [qtp2050525584-35] WARN  o.e.j.ee10.servlet.ServletChannel - handleException /pdf/api/v1/misc/ocr-pdf java.io.IOException: Command process failed with exit code 5. Error message:   DEBUG ocrmypdf - ocrmypdf 16.1.1
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 5.3.4
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 10.3.1
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = [DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 0:(null) score is 0.390008
[DS] Selected Device[1]: "(null)" (Native)
List of available languages in "/usr/share/tessdata/" (1):
eng

  DEBUG ocrmypdf.helpers - pikepdf mmap enabled
  ERROR ocrmypdf._pipelines._common - ExitCodeException
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py", line 249, in cli_exception_handler
    return fn(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 166, in _run_pipeline
    check_requested_output_file(options)
  File "/usr/lib/python3.12/site-packages/ocrmypdf/_validation.py", line 310, in check_requested_output_file
    raise OutputFileAccessError(
ocrmypdf.exceptions.OutputFileAccessError: Output file location (/tmp/output_16848536940110331072.pdf) is not a writable file.
`
