### ISSUE TITLE
[Feature Request]: Integrity check

### ISSUE THREAD

**Issue by IkelAtomig** [Stirling-Tools/Stirling-PDF#1992] opened 2024-10-05 08:35 UTC
### Feature Description

An integrity check based on a specific value to know if a public instance is using docker image as is or modified the image to save files that are meant to be not saved at all violating user privacy.

### Why is this feature valuable?

It assures user's data privacy and confidentiality.

### Suggested Implementation

This will show a specific hash of the current Docker image in either corner of the app webpage. Which will then check with the hash that is on a file in this GitHub repository, separate file corresponding to separate point releases. If the hash matches, The Icon says “Private & Secure”. If not, “Not secure :warning:” when clicking on it, it will explain that server using the open source software might have modified the source code and is not recommend to use this instance of server to protect your privacy.

### Additional Information

I think config files should also be considered for hash calculation.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment] 2024-10-05 09:10
I've thought about this before but decided against it as it gives a false sense of security 
At the end of the day anyone with the knowledge to change the source code has the knowledge on how to spoof this check and make it appear safe

**Comment by sbplat** [comment] 2024-10-10 13:44
Couldn't they just modify the check or remove it completely?

**Comment by ummm288** [comment] 2024-10-24 22:56
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Frooodle** [comment] 2024-11-12 22:18
Sadly going to close this ticket as I don't think its achievable and only will give false hope

**Closed by Frooodle** 2024-11-12 22:18 UTC
Labels: enhancement

**Comment by sbplat** [comment] 2024-11-21 13:12
The problem is that the binary could be modified (so it shows secure when the hashes don't match). If you know the binary has never been tampered with, then it's fine, but how can you guarantee that. Unless they manually verify the binary checksum, but at this point why not just verify the checksum of the docker image itself?
