### ISSUE TITLE
Remove Blanks broken in 0.20.2

### ISSUE THREAD

**Issue by TheOneValen** [Stirling-Tools/Stirling-PDF#752] opened 2024-01-29 08:35 UTC
Hi!

I use the StirlingPDF api for my scanner workflow. I use different endpoints in my flow (ocr, merge, remove blanks... etc.). This is maybe related to #729 

I Use the **docker** version of StirlingPDF in version 0.20.1

My Pipeline goes like this

Scan -> OCR -> merge/split (whatever, using sterling seperator) -> optimize -> remove blanks ->pdfa

The remove blanks step seems still to be broken. As in the related issue I set Threshold to 15 and White Percent to 95.

When using the scanner output direcly on remove blanks, it returns me a broken PDF file. Here is the file to reproduce.

[After Scan.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14081640/After.Scan.pdf)

When using the step after OCR or after Optimize (compress-pdf) I get an 500 error. For Reproducing here are the files:
[Broken after OCR.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14081671/Broken.after.OCR.pdf)
[BROKEN after optimize.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14081672/BROKEN.after.optimize.pdf)

I hope I provided all the infos you need, when you need more info please ask.

Thank you and have a nice day!

**Comment by sbplat** [comment] 2024-01-29 15:10
I'm able to reproduce this bug. Seems to be caused by a `StackOverflowError`, so I think it's a different bug.

**Comment by TheOneValen** [comment] 2024-01-31 18:24
Thank you for your hard work :)

**Comment by TheOneValen** [comment] 2024-02-03 23:32
Using 0.20.2 the remove blanks step is still broken. If a page gets removed I get an empty 440byte file with no pages at all. You can try it using the "AfterScan" document and a setting that would not remove any page (white 255 and 100% whiteness), but any other setting will yield the same result. Should I open a new bug?

**Comment by sbplat** [comment] 2024-02-04 01:08
Is it with the same document?

**Comment by sbplat** [comment] 2024-02-04 01:23
Seems to be related to `detect-blank-pages.py`. For some reason, it's detecting the page as completely white when it isn't.
```
s.s.SPDF.utils.ProcessExecutor - Page has white pixel percent of 100.0
```

**Comment by Frooodle** [comment] 2024-02-10 08:30
Closed in next release :)

**Closed by Frooodle** 2024-02-10 08:30 UTC
Labels: bug
