### ISSUE TITLE
In version 0.22.8, the api does not exist, convert error: PDF to HTML

### ISSUE THREAD

**Issue by kevin2yl** [Stirling-Tools/Stirling-PDF#1082] opened 2024-04-18 03:03 UTC
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/142221254/ba475fa8-3232-4e50-8ead-1165b394e15d)

**Comment by sbplat** [comment] 2024-04-19 01:47
Duplicate of #1037. This will be fixed in the next release.

**Closed** 2024-04-19 01:47 UTC
