### ISSUE TITLE
Processing status

### ISSUE THREAD

**Issue by kbkozlev** [Stirling-Tools/Stirling-PDF#724] opened 2024-01-19 13:20 UTC
When an operation is being performed, there is no information regarding the state of the work.

For example, if I'm merging 10 png's into a PDF, it would be nice to have some kind of message, such as “1.png being processed”, or “File 1/10 is being processed”. Currently, only the button changes to “processing”, but no further info.

For long operations with hundreds of pages, this will be very helpful

**Comment by sbplat** [comment] 2024-01-19 15:25
V2 currently offers workflow progress, but is still WIP.

**Comment by Frooodle** [comment] 2024-12-05 16:16
Duplicate of https://github.com/Stirling-Tools/Stirling-PDF/issues/149

**Closed by Frooodle** 2024-12-05 16:16 UTC
Labels: enhancement
