### ISSUE TITLE
Excel to PDF feature 

### ISSUE THREAD

**Issue by yongcrane** [Stirling-Tools/Stirling-PDF#684] opened 2024-01-10 07:24 UTC
I'm trying to use the PDF function.
Internal Server Error: Cannot run program "unoconv": CreateProcess error=2, an error occurred. I'm currently using Microsoft 365 Apps for enterprise.
Do I need to install LibreOffice to install unoconv?
What is the problem?
How can I deal with this problem?

**Comment by sbplat** [comment] 2024-01-10 14:30
Yes, you would need to install LibreOffice.

**Comment by yongcrane** [comment] 2024-01-11 07:17
already LibreOffice. but Cannot run program "unoconv": CreateProcess error=2,

**Comment by yongcrane** [comment] 2024-01-11 08:55
![test](https://github.com/Stirling-Tools/Stirling-PDF/assets/127723308/0db85b35-e550-43d5-a1af-fd3b5e24e49f)
Do I need to specify this path?

**Comment by Frooodle** [comment] 2024-01-11 09:28
No you can just add the relative programs to your PATH environment variable for windows

**Comment by sbplat** [comment] 2024-01-12 15:47
This looks like a duplicate of #524 and #614. If you're not using Docker, did you install all the listed dependencies?

**Closed** 2024-01-31 19:52 UTC
Labels: question

**Comment by Gaini-Laxman** [comment] 2024-03-19 15:49
I added path and all dependencies added but still same issue below 
Internal Server Error:Cannot run program "unoconv": CreateProcess error=2, The system cannot find the file specified
