### ISSUE TITLE
Bug - PDF Splitting File Size

### ISSUE THREAD

**Issue by lawfulsoftware** [Stirling-Tools/Stirling-PDF#400] opened 2023-10-03 21:18 UTC
I split a test 11-page PDF file with a file size of 545 KB using the split-pages API endpoint with a pageNumbers value of 1n.

The output is 11 PDF files in a ZIP file however the total size of the ZIP file is 5,399 KB and the uncompressed size of **each** PDF file is between 516 KB and 519 KB which is nearly the size of the entire original file.

I am using the latest alpha Docker container.

**Comment by Frooodle** [comment] 2023-10-03 21:59
Just added a quick fix, can you try pull the latest alpha version once it uploads in 2-3 mins?

**Comment by Frooodle** [comment] 2024-04-28 22:06
closing and duplicate of 401 really

**Closed by Frooodle** 2024-04-28 22:06 UTC
Labels: bug
