### ISSUE TITLE
Extract table from PDF to CSV ERROR

### ISSUE THREAD

**Issue by 247no2** [Stirling-Tools/Stirling-PDF#848] opened 2024-02-23 07:30 UTC
Hello, I have a PDF with a table in it, I would like to use the function. But when I upload the PDF and press Extract, I get an error message: Internal Server Error:No table detected, no headers or records found.

What can I do to use the function?

"![Unbenannt](https://github.com/Stirling-Tools/Stirling-PDF/assets/124701569/e3370efd-2dd3-4787-b33d-0de092ed2da4)"

**Comment by 247no2** [comment] 2024-02-26 07:22
> Handelt es sich bei der Tabelle um ein Bild?

No is a PDF file.

**Comment by emiraliabdur** [comment] 2024-03-07 16:43
I can look into, how can I assign it and start investigating?

**Comment by sbplat** [comment] 2024-03-07 16:52
Sure, I've assigned it to you.

@247no2 could you share the PDF (or another reproducible sample) here so @emiraliabdur can investigate? Thanks!

**Comment by emiraliabdur** [comment] 2024-03-07 17:36
I think, I was able to reproduce with this file 
[table.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14527928/table.pdf)

`
18:37:33.256 [http-nio-8080-exec-7] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.Exception: No table detected, no headers or records found] with root cause
java.lang.Exception: No table detected, no headers or records found
	at stirling.software.SPDF.controller.api.converters.ExtractController.PdfToCsv(ExtractController.java:86)
`

**Comment by emiraliabdur** [comment] 2024-03-08 09:18
It seems that this functionality doesn't work properly, there are some different issues:

1. If the number of empty lines is greater than nonempty in pdf, then  we get this error
2. PDF with table and text is converted wrongly, as all text is parsed and in the result some parts are missing:
[ast_sci_data_tables_sample.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14535979/ast_sci_data_tables_sample.pdf)
[ast_sci_data_tables_sample_extracted(2).csv](https://github.com/Stirling-Tools/Stirling-PDF/files/14535983/ast_sci_data_tables_sample_extracted.2.csv)
3. PDF with multiple table is also converted wrongly:
[29-1_schollaert-uz_examples.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14535994/29-1_schollaert-uz_examples.pdf)
[29-1_schollaert-uz_examples_extracted.csv](https://github.com/Stirling-Tools/Stirling-PDF/files/14535997/29-1_schollaert-uz_examples_extracted.csv)
4. PDF with table containing multiline cells

It might need some rework, maybe this [repo]() could be reused

**Comment by 247no2** [comment] 2024-03-11 12:09
I hope that this problem can be solved :-)
Thanks for that

**Comment by 247no2** [comment] 2024-04-04 09:37
Is there anything new in this regard?

**Comment by karlellis** [comment] 2024-07-10 10:18
Hi, I have the same issue.
Windows 10 22H2 x64
StirlingPDF v0.26.1 .exe

Stack Trace:
java.lang.Exception: No table detected, no headers or records found
	at stirling.software.SPDF.controller.api.converters.ExtractController.PdfToCsv(ExtractController.java:86)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:925)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:830)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:61)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:814)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:431)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:619)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[Sample Table.pdf](https://github.com/user-attachments/files/16159335/Sample.Table.pdf)

**Comment by Frooodle** [comment] 2024-07-31 20:01
Going to close this as plan to migrate to 
https://github.com/Stirling-Tools/Stirling-PDF/issues/1614

**Closed by Frooodle** 2024-07-31 20:01 UTC
Labels: needs investigation
