### ISSUE TITLE
Browser download always blocks file

### ISSUE THREAD

**Issue by MarcS1975** [Stirling-Tools/Stirling-PDF#887] opened 2024-03-09 07:21 UTC
My Chrome browser always prevents the PDF from downloading. Is there a way to permanently allow this?

**Comment by Frooodle** [comment] 2024-03-09 08:07
Do you have any screenshots or context of what you are on about? Also are you using nginx or anything

**Comment by anvaya-solanki** [comment] 2024-03-18 14:24
You can try this:

1. Open Chrome Settings.
2. Go to Privacy and Security and then Site Settings.
3. Find PDF Documents settings.
4. Enable "Download PDF files instead of automatically opening them in Chrome."

**Comment by Frooodle** [comment] 2024-03-18 17:31
Stirling pdf has a settings cog menu in top right

Have you changed the setting within that to be "download file?"
Is the above still required after that change?

**Comment by Softbox44** [comment] 2024-03-21 11:11
there is no "download file" when clicking the cog

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/163422442/84f6d4d0-271c-4318-b175-5c719b6c7292)

**Comment by Frooodle** [comment] 2024-03-21 12:08
> there is no "download file" when clicking the cog
> 
> ![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/163422442/84f6d4d0-271c-4318-b175-5c719b6c7292)
> 

"Choose download option:"
"Open in same window"

Changing that should stop it opening in same window

**Comment by der8en** [comment] 2024-04-16 16:01
I use Vivaldi Browser and "Download File" also dosnt work anymore. Firefox is normal.
No error in Console log.

Only:
Deprecated feature used
Unload event listeners are deprecated and will be removed.
downloader.js:261

**Comment by Frooodle** [comment] 2024-08-24 15:28
Do you still see this issue, and does it also happen for installs like 
https://stirlingpdf.io/


particularly wondering on
> In Chrome the download works but tells me the download is insecure, luckily I can override it, but it's not ideal.

as I cant reproduce this, closing ticket for now, please let me know!

**Closed by Frooodle** 2024-08-24 15:28 UTC
Labels: Bug, needs investigation, more-info-needed
