### ISSUE TITLE
[Feature Request]: Split file on QR Codes

### ISSUE THREAD

**Issue by tymanthius** [Stirling-Tools/Stirling-PDF#1737] opened 2024-08-22 19:03 UTC
### Feature Description

split PDF's on QR codes. The number of pages and even number of QR's can vary. So maybe have the QR code name the split even?

Possibly have the first QR code be a Folder Name to store all the splits in?

Example:

Pge 1 is a barcode with file name - use that to create a top level folder with File Name and that page is never used again.
Page 2 is a QR code that says 'Buyer'
Pages 3-15 are for the Buyer and get split out into a file named Buyer in the File Name folder
Page 16 is a QR code that says 'Attny'
Pages 17-8 are for the attny and get split out to a file named Attny in the File Name folder.

Proceed until all pages are done.

### Why is this feature valuable?

You can feed a bunch of 'standard' documents to scanner at once and have the QR codes divide the PDF into named files.  Useful in mass scanning scenarios or when only certain parts of a total file need to go to certain people/folders.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment] 2024-12-13 13:07
duplicate of #1073

**Closed by Frooodle** 2024-12-13 13:07 UTC
Labels: enhancement
