### ISSUE TITLE
[Bug]: Pipeline in watched folders is not triggered with images

### ISSUE THREAD

**Issue by TKone7** [Stirling-Tools/Stirling-PDF#1552] opened 2024-07-10 07:22 UTC
### The Problem

When using the watched folder feature in combination with the img-to-pdf stage (with `.png` input files) the folder is not processed.

**Steps to reproduce**
1. create folder for task `/pipeline/watchedFolders/reproduction`
2. place the following `config.json` in the folder:
```json
{
  "name": "reproduction",
  "pipeline": [
    {
      "operation": "/api/v1/convert/img/pdf",
      "parameters": {
        "fitOption": "maintainAspectRatio",
        "colorType": "color",
        "autoRotate": true,
        "fileInput": "automated"
      }
    }
  ],
  "_examples": {
    "outputDir": "{outputFolder}/{folderName}",
    "outputFileName": "{filename}-{pipelineName}-{date}-{time}"
  },
  "outputDir": "{outputFolder}",
  "outputFileName": "{pipelineName}"
}
```
3. place one (or more) PNG files in the same folder

**Actual  behaviour**
The folder is not processed at all.

**Expected behaviour**
The folder should be processed and the images should be converted into a PDF and placed in the output folder.

Additional
I don't understand Java very well but it seems to me the issue was introduced by #1282. It looks to me as there is a filter that only looks at PDFs.

### Version of Stirling-PDF

0.25.1 until latest

### Last Working Version of Stirling-PDF

0.25.0

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by frankyman88** [comment] 2024-07-19 22:13
Having the same problem, thought I was going crazy!

**Comment by Frooodle** [comment] 2024-07-19 23:00
Will be fixed in next update! 
Just stuck fixing some new bugs caused by other updates at moment so can't release

**Comment by Frooodle** [comment] 2024-08-24 15:11
finally will be fixed next udpate..

**Closed by Frooodle** 2024-08-24 15:11 UTC
Labels: Bug
