### ISSUE TITLE
[Bug]: Mouse-over of 'favourites' missing text in Chrome on Linux

### ISSUE THREAD

**Issue by wayneoutthere** [Stirling-Tools/Stirling-PDF#2364] opened 2024-11-29 21:10 UTC
### Installation Method

Docker

### The Problem

Hi all
When I mouse-over 'favourites' on the very top toolbar of the [the website](https://stirlingpdf.io/) I see 'no favourites added'.
On my downloaded docker/podman image, when i moues over I get a blank in the dialogue window.  Here is an image of what I'm seeing:

![stirling_favourites_missing_string](https://github.com/user-attachments/assets/d5c5f474-51cc-4c31-8333-92bdb021dee2)

This seems to only happen in an older version of Chromium (version 121.0.6167.139) (I was testing in this browser) not in Firefox so seems to be some bug in there.

Hope that helps.

### Version of Stirling-PDF

0.34.0

### Page Where the Problem Occurred

http://localhost:8080

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ludy87** [comment] 2024-12-06 20:16
@Frooodle is a duplicate of https://github.com/Stirling-Tools/Stirling-PDF/issues/2225

**Closed** 2024-12-06 20:40 UTC
Labels: Bug, Front End
