### ISSUE TITLE
Merge Tool shows duplicate rows when selecting sort by name

### ISSUE THREAD

**Issue by joe2k1** [Stirling-Tools/Stirling-PDF#670] opened 2024-01-07 15:46 UTC
Hello,

After taking the latest update from January 6, 2024 I noticed a minor issue when sorting (by name) merged PDFs. Please see my screenshots below:

![IMG_5415](https://github.com/Stirling-Tools/Stirling-PDF/assets/52223386/8de421f6-6be7-49a9-857e-29404adab56c)
![IMG_5416](https://github.com/Stirling-Tools/Stirling-PDF/assets/52223386/740b465f-a7a7-478c-a696-9479487ea9a5)

Please that in the example above and other scenarios you get the correct number of merged PDFs when you select Merge. (The above scenario produced 3 PDFs together)

**Comment by sbplat** [comment] 2024-01-07 16:38
Duplicate of #660

**Closed by sbplat** 2024-01-07 16:38 UTC
