### ISSUE TITLE
[Feature Request]: Progress Indicator for "Compress PDF" Task

### ISSUE THREAD

**Issue by bipenett** [Stirling-Tools/Stirling-PDF#1935] opened 2024-09-19 16:54 UTC
### Feature Description

Hello!

First of all, I want to thank the development team for creating such a great tool. I've been using Sritling PDF extensively, and it has made my PDF workflow much easier.

I'd like to suggest a feature for the Compress PDF tool. Currently, after initiating the compression, there's no indication of the task's progress. For larger files, it's difficult to tell whether the process is still ongoing or if it's stuck.

Suggested Feature:

- Add a progress bar or percentage indicator that displays the current state of the compression process.

- This could help users gauge how long the task might take and give feedback that the tool is working in real-time.

This feature would greatly improve the user experience, especially when working with large files. Thanks again for your time and consideration!

Best regards!

### Why is this feature valuable?

This feature would greatly improve the user experience, especially when working with large files

### Suggested Implementation

Add a progress bar or percentage indicator that displays the current state of the compression process.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment] 2024-12-05 16:16
Duplicate of https://github.com/Stirling-Tools/Stirling-PDF/issues/149

**Closed by Frooodle** 2024-12-05 16:16 UTC
Labels: enhancement
