### ISSUE TITLE
Function "Add Image" - Image placed wrongly if PDF is a landscape PDF

### ISSUE THREAD

**Issue by hhlotter** [Stirling-Tools/Stirling-PDF#1132] opened 2024-04-27 15:25 UTC
Only if the PDF is Portrait, the image is placed correctly. When it is a landscape PDF, you can place the image but on the resulting produced pdf the image appears turned by 90 degrees and at the wrong place (the place if it was a portrait PDF).

**Comment by Frooodle** [comment] 2024-04-28 21:56
Duplicate of #217

**Closed** 2024-04-28 21:56 UTC
Labels: bug, good first issue
