### ISSUE TITLE
Display of App Version in Settings

### ISSUE THREAD

**Issue by 463** [Stirling-Tools/Stirling-PDF#692] opened 2024-01-10 16:03 UTC
In v0.19.1 the App Version is not shown.

![grafik](https://github.com/Stirling-Tools/Stirling-PDF/assets/7769231/d8e97afe-2405-4aa1-a75c-2d347b993096)

**Comment by sbplat** [comment] 2024-01-10 16:54
Duplicate of #668.

**Closed by sbplat** 2024-01-10 16:54 UTC
